[package]
name = "pipeline-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
inventory = "0.3.15"
once_cell = "1.20.2"
quick-xml = { version = "0.37.1", features = ["serialize"]}
serde = { version = "1.0.215", features = ["derive"] }
